"""SGRS real-time event transport (NATS)."""

from .api import EventsApi, NatsConfig, NatsNotConfiguredError, NatsNotConnectedError
from .schema import (
    BaseEvent,
    SgrsEvent,
    ScopeEvent,
    ModelEvent,
    AgentEvent,
    ScopeCreatedEvent,
    ScopeUpdatedEvent,
    ScopeDeletedEvent,
    FinalityChangedEvent,
    FinalityNearFinalEvent,
    FinalityFinalEvent,
    VetoActivatedEvent,
    VetoLiftedEvent,
    ModelConnectedEvent,
    ModelRevokedEvent,
    AgentHeartbeatEvent,
    AgentTaskStartedEvent,
    AgentTaskCompletedEvent,
    AgentTaskFailedEvent,
    create_base_event,
)
from .subjects import subjects, all_tenant_subjects, audit_stream_name, scope_stream_name

__all__ = [
    "EventsApi",
    "NatsConfig",
    "NatsNotConfiguredError",
    "NatsNotConnectedError",
    "BaseEvent",
    "SgrsEvent",
    "ScopeEvent",
    "ModelEvent",
    "AgentEvent",
    "ScopeCreatedEvent",
    "ScopeUpdatedEvent",
    "ScopeDeletedEvent",
    "FinalityChangedEvent",
    "FinalityNearFinalEvent",
    "FinalityFinalEvent",
    "VetoActivatedEvent",
    "VetoLiftedEvent",
    "ModelConnectedEvent",
    "ModelRevokedEvent",
    "AgentHeartbeatEvent",
    "AgentTaskStartedEvent",
    "AgentTaskCompletedEvent",
    "AgentTaskFailedEvent",
    "create_base_event",
    "subjects",
    "all_tenant_subjects",
    "audit_stream_name",
    "scope_stream_name",
]
